apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: angular-app
  namespace: argocd
spec:
  destination:
    namespace: angularwebapp
    server: https://kubernetes.default.svc
  source:
    path: manifest
    repoURL: 'https://github.com/ASHOKGANI6300/angular-mithuntechnologies'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
